name: Deploy to Hugging Face Space

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Push to Hugging Face
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git clone https://huggingface.co/spaces/abhishek-chauhan-97/clinical-rag hf-space
          rsync -av --exclude='.git' ./ hf-space/
          cd hf-space
          git add .
          git commit -m "Sync from GitHub" || echo "No changes to commit"
          git push https://user:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/abhishek-chauhan-97/clinical-rag main
